version: '3.1'

services:
  python_script:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
