"""Add municipality ruian as foreign key to official notice board

Revision ID: 1ac54fa65e2c
Revises: d1c2828d49cd
Create Date: 2022-04-10 15:29:07.293660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac54fa65e2c'
down_revision = 'd1c2828d49cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_notice_board', sa.Column('municipality_ruian', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'official_notice_board', 'municipality', ['municipality_ruian'], ['ruian'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'official_notice_board', type_='foreignkey')
    op.drop_column('official_notice_board', 'municipality_ruian')
    # ### end Alembic commands ###
