"""Change some attributes back to not nullable

Revision ID: 5f25d8f5a7d1
Revises: 9e784c995900
Create Date: 2022-04-25 23:18:04.429645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f25d8f5a7d1'
down_revision = '9e784c995900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('municipality', 'has_extended_competence',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notice', 'description_missing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notice', 'reference_number_missing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notice', 'reference_number_missing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notice', 'description_missing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('municipality', 'has_extended_competence',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
