"""some changes

Revision ID: 9022fce9d97c
Revises: 5f25d8f5a7d1
Create Date: 2022-05-04 15:37:05.863198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9022fce9d97c'
down_revision = '5f25d8f5a7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('revision', sa.String(length=100), nullable=True))
    op.add_column('official_notice_board', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('official_notice_board', 'name')
    op.drop_column('notice', 'revision')
    # ### end Alembic commands ###
