"""delete Mapper

Revision ID: 9be287e34ba0
Revises: 9022fce9d97c
Create Date: 2022-05-06 13:35:17.716282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be287e34ba0'
down_revision = '9022fce9d97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapper',
    sa.Column('ruian', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ico', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ruian', name='mapper_pkey'),
    sa.UniqueConstraint('ico', name='mapper_ico_key'),
    sa.UniqueConstraint('ruian', name='mapper_ruian_key')
    )
    # ### end Alembic commands ###
