"""Add extended competence to municipality. Add description and ref_number to notice

Revision ID: 9e784c995900
Revises: fc790958f463
Create Date: 2022-04-25 23:08:34.138214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e784c995900'
down_revision = 'fc790958f463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipality', sa.Column('has_extended_competence', sa.Boolean(), nullable=True))
    op.add_column('notice', sa.Column('description', sa.String(length=50), nullable=True))
    op.add_column('notice', sa.Column('description_missing', sa.Boolean(), nullable=True))
    op.add_column('notice', sa.Column('reference_number', sa.String(length=50), nullable=True))
    op.add_column('notice', sa.Column('reference_number_missing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'reference_number_missing')
    op.drop_column('notice', 'reference_number')
    op.drop_column('notice', 'description_missing')
    op.drop_column('notice', 'description')
    op.drop_column('municipality', 'has_extended_competence')
    # ### end Alembic commands ###
